Repository gridfinity/leaktestfe, pull requests merged in 2020-12, with the labels that each got.

#2 Mergify: configuration update
  .mergify.yml
Labels: configuration

#8 Add a Codacy badge to README.md
  README.md
Labels: automation, bot, documentation, enhancement

#9 Add DeepSource Badge
  README.md
Labels: documentation, enhancement

#10 README formatting
  README.md
Labels: low-priority

#12 Add go.gridfinity.com link
  README.md
Labels: documentation, low-priority

#13 Tickgit badge
  README.md
Labels: automation, bot, cleanup, documentation, low-priority

#14 Add badges
  README.md
Labels: automation, documentation, enhancement, low-priority

#15 ISC License Badge
  README.md
Labels: automation, documentation, enhancement

#16 Add badges
  README.md
Labels: automation, documentation, enhancement, formatting

#17 Badges
  README.md
Labels: automation, enhancement, low-priority

#18 Remove extra badge
  README.md
Labels: bug
